# BF-BukkitTelnet v.05 Configuration File

# Address to listen on, leave blank for all
address: ''

# Port to bind to:
port: 8765

# Main connection password, must be defined
password: 'stupid55555555555555555555555555'

# List of admins / IPs that don't have to use the password
admins:
  xBarkPuppy1:
    - 74.171.175.7
  Frab:
    - 176.56.237.227
  tizly:
    - 71.47.67.103
  teknosquetSilver:
    - 751.46.66.321





# Frab is YAZANYT
